version: "3.6"

services:
 postgres:
  image: postgres:12
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 blockexchange:
  image: golang:1.16.0-alpine
  depends_on:
   - postgres
  volumes:
   - ".:/data"
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=5432
   - LOGLEVEL=debug
   - BLOCKEXCHANGE_NAME=My-Blockexchange
   - BLOCKEXCHANGE_OWNER=yourname
   - BLOCKEXCHANGE_KEY=abcdefSecretKey
   - BLOCKEXCHANGE_TEST_DATA=true
   - BASE_URL=http://localhost:8080
   - WEBDEV=true
  ports:
   - "8080:8080"
  working_dir: /data
  command: ["go", "run", "."]

 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.4.0
  user: root
  volumes:
   - "world_data:/root/.minetest/worlds/world"
   - "./dev/worldmods:/root/.minetest/worlds/world/worldmods"
   - "./dev/minetest.conf:/etc/minetest/minetest.conf"
  ports:
   - "30000:30000/udp"

 mod-integration-test:
  image: registry.gitlab.com/minetest/minetest/server:5.4.0
  user: root
  volumes:
   - "./dev/minetest-test.conf:/etc/minetest/minetest.conf:ro"
   - "./dev/worldmods:/root/.minetest/worlds/world/worldmods"

 integration-test:
  image: golang:1.16.0
  depends_on:
   - postgres
  volumes:
   - ".:/data"
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=5432
   - LOGLEVEL=debug
  working_dir: /data
  command: ["go", "test", "./..."]

volumes:
  postgres: {}
  world_data: {}
