version: "3.6"

services:
 postgres:
  image: postgres:12
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 blockexchange:
  build:
   context: .
   dockerfile: Dockerfile-dev
  depends_on:
   - postgres
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=5432
   - BLOCKEXCHANGE_NAME=My-Blockexchange
   - BLOCKEXCHANGE_OWNER=yourname
   - BLOCKEXCHANGE_KEY=abcdefSecretKey
   - BASE_URL=http://localhost:8080
  volumes:
   - "node_modules:/data/node_modules"
   - "./src:/data/src"
   - "./public:/data/public"
  ports:
   - "8080:8080"

 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.3.0
  user: root
  volumes:
   - "world_data:/root/.minetest/worlds/world"
   - "./dev/worldmods:/root/.minetest/worlds/world/worldmods"
   - "./dev/minetest.conf:/etc/minetest/minetest.conf"
  ports:
   - "30000:30000/udp"

 selenium:
  image: selenium/standalone-firefox:83.0
  ports:
   - 4444:4444

 e2e-test:
  build: e2e
  depends_on:
   - selenium
   - blockexchange

volumes:
  postgres: {}
  node_modules: {}
  world_data: {}
