openapi: 3.0.0
info:
  title: Blockexchange API
  description: blockexchange cloud schema exchanger api docs
  version: latest
servers:
  - url: https://blockexchange.minetest.land/api
    description: blockexchange.minetest.land central server

components:
  schemas:
    Info:
      type: object
      properties:
        api_version_major: 
          type: number
        api_version_minor: 
          type: number
        name:
          type: string
        owner:
          type: string
paths:
  /info:
    get:
      tags: ["info"]
      summary: Returns some infos about the running blockexchange
      responses:
        '200':    # status code
          description: info object
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Info'
  /token:
    post:
      tags: ["token"]
      summary: exchange login credentials with a token
      responses:
        '200':
          description: the resulting jwt token
          content:
            text/plain:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c