name: coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: enter
          POSTGRES_DB: postgres
    env:
      PGUSER: postgres
      PGPASSWORD: enter
      PGHOST: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      LOGLEVEL: debug
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        cd public && npm ci && cd ..
        go test ./... -tags=integration -coverprofile=profile.cov
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
