name: docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@master

    - name: integration-test
      run: ./integration-test.sh

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: blockexchange/blockexchange
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true

    - name: deploy central
      run: curl -X POST -F token=6e0aa9d77b43c78c268a0c7e7fabb6 -F ref=master https://dev.rudin.io/api/v4/projects/68/trigger/pipeline
