name: integration_test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare files
      run: |
        cd public && npm ci && cd ..
    - name: Start  services
      run: |
        docker-compose up -d postgres
        sleep 10
        docker-compose up -d blockexchange
    - name: Execute tests
      run: |
        docker-compose up mod-integration-test
