name: jshint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt-get install -y nodejs npm
    - name: install
      run: npm i
    - name: jshint frontend
      run: npm run jshint_frontend
    - name: jshint backend
      run: npm run jshint_backend
