name: selenium

on:
  push:
    paths:
      - "src/**"
      - "public/**"
      - "migrations/**"
      - "e2e/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: set up environment
      run: |
        docker-compose up -d postgres
        sleep 5
        docker-compose up -d blockexchange selenium
        sleep 5

    - name: run tests
      run: docker-compose up --exit-code-from e2e-test e2e-test

    - name: clean up
      run: docker-compose down
